HabitHack/main/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy, path
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
)
from . import views
from . import home_views

#DO NOT DELETE COMMENTED LINES! (STILL TESTING)

app_name = 'main'
urlpatterns = [
    #url(r'^$', views.index, name = 'index'),
    #url(r'^welcome/$', views.index, name = 'index'),
    url(r'^$', views.MainView.as_view(), name = 'index'),
    url(r'^welcome/$', views.MainView.as_view(), name = 'index'),
    #url(r'^login/$', views.user_login, name='login'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    #url(r'^login/$', views.MainView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('main:index')), name='logout'),
    #url(r'^register/$', views.register, name='register'),
    url(r'^register/$', views.RegistrationFormView.as_view(), name='register'),
    #url(r'^register/$', views.MainView.as_view(), name='register'),
    path('user/<username>/', views.user_profile, name='user'),
    path('settings/', views.edit_user_profile, name='edit_user'),
    path('home/', home_views.home, name='home'),
    path('increment_counter/', home_views.increment_counter, name='increment_counter'),
    path('habits/<habit_id>/', home_views.edit_habit, name='edit_habit'),
    path('add_habit/', home_views.add_habit, name='add_habit'),
    path('delete_habit/<habit_id>', home_views.delete_habit, name='delete_habit'),
]

HabitHack/main/templates/main/add_habit.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block content %}
<form enctype="multipart/form-data" action="" method="post">
  {% csrf_token %}
  {{ habit_form.as_p }}
  <button type="submit">Add new habit</button>
</form>
{% endblock %}

HabitHack/main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  {% block extra_head %}
  {% endblock %}

  {% block scripts %}
  {% endblock %}

  <!-- title may be moved to specific pages -->
  <title>Habit Hack</title>
</head>

<body>
<div id="site-wrapper">

  <header>
    <h1>HabitHack</h1>

    <nav><ul>
      {% if request.user.is_authenticated %}
        <li id="login-button"><a href="{% url "main:logout" %}"></a></li>
        <li><a href="{% url 'main:user' username=request.user.username %}">Profile</a></li>
        <li><a>Groups</a></li>
        <li><a href="{% url 'main:home' %}">Home</a></li>
      {% else %}
        <li>for active people who want to keep track of their routines</li>
      {% endif %}
    </ul></nav>

    <div id="underline-header"></div>
  </header>

  {# The Document Body #}
  <main id="content-wrapper">
    {% block content %}
    {% endblock content %}
  </main>

  <footer></footer>
</div>
</body>
</html>

HabitHack/main/templates/main/edit_habit.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block content %}
<form enctype="multipart/form-data" action="" method="post">
  {% csrf_token %}
  {{ habit_form.as_p }}
  <button type="submit">Edit habit</button>
</form>
<a href="{% url 'main:delete_habit' habit_id=habit_id %}"><button>Delete habit</button></a>
{% endblock %}

HabitHack/main/templates/main/edit_profile.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'edit_profile.css' %}">
{% endblock %}

{% block content %}
<form enctype="multipart/form-data" action="" method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ user_profile_form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endblock %}

HabitHack/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'calendar.css' %}">
{% endblock %}

{% block scripts %}
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<script src="{% static 'js/helperFunctions.js' %}"></script>
<script src="{% static 'js/Record.js' %}"></script>
<script src="{% static 'js/Habit.js' %}"></script>

<script>
  let habits = [];
  let id;
  let weekdays;
  let numRepeats;
  let habit; 
  let rec; 
</script>

{% for habit in habits %}
  <script>
      id = "{{habit.id}}";
      name = "{{habit.name}}";
      weekdays = "{{habit.weekdays}}".split(",").map(str => parseInt(str));
      numRepeats = parseInt("{{habit.num_repeats}}");
      habit = new Habit(id, name, new Set(weekdays), numRepeats);
  </script>
  {% for key, value in habit.history.items %}
    <script>
        console.log("{{key}}");
        habit.addRecord("{{key}}", parseInt("{{value}}"));
    </script>
  {% endfor %}

  <script>
      console.log(habit);
      habits.push(habit);
  </script>
{% endfor %}

<script src="{% static 'js/calendar.js' %}"></script>
{% endblock %}

{% block content %}
<div id="home-wrapper">

  <a href="{% url 'main:add_habit' %}" id="add-habit-btn">
    <span>Add New Habit</span>
  </a>

  <div id="tracker-wrapper">
    <div id="wrapper-wrapper">
      <button id="prev-week">&lt</button>
      <span id="month-name">Month</span>
      <button id="next-week">&gt</button>
    </div>
    <div id="calendar-wrapper">
      <table id="habits-table"></table>
    </div>
  </div>
</div>
</table>
{% endblock %}

HabitHack/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock %}

{% block content %}
<div class="forms">
  <div class="login">
    <img src="{% static 'images/layer-1.png' %}" alt="log in picture">
    <form action="{% url 'main:login' %}" method="post">
      {% csrf_token %}
      {{ login_form.as_p }}
      <button type="submit">Login</button>
    </form>
    <br>
    <a href="url">Forgot your password?</a>
    <br>
    <button type="button" id="fb">Log in with Facebook</button>
  </div>
  <div class="register">
    <img src="{% static 'images/layer-2.png' %}" alt="register picture">
    <form action="{% url 'main:register' %}" method="post">
      {% csrf_token %}
      {{ register_form.as_p }}
      <button type="submit">Register</button>
    </form>
  </div>
</div>
{% endblock %}

HabitHack/main/templates/main/login_form.html
{% extends 'main/index.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login" /><br/>
    </form>
{% endblock %}

HabitHack/main/templates/main/profile.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}

{% block content %}
<div class="Photo">
  <!--profile photo-->
  <img src="{{ profile.profile_photo.url }}"></img></div>
  <div class="Name"><!--username-->
  {% if user.first_name or user.last_name %}
    {{ user.first_name }} {{ user.last_name }}
  {% else %}
    *Your name should be here*
  {% endif %}
  </div>
<div class="Town-country"><!--user location-->
  {% if profile.city or profile.country %}
    {{ profile.city }}, {{ profile.country }}
  {% else %}
    *Your location should be here, please add it in your settings*
  {% endif %}
</div>
<div class="desc">
  <!--profile description-->
  {{ profile.description }}
</div>
{% if request.user != user %}
<div class="mssg_button">
  <div class="mssg_text">
    Send message
  <!--mail icon-->
  <div class="mssg_img">
  <img src="https://i.imgur.com/SeiqqQj.png"
  width="32" height="24" /></div>
  </div>
</div>
{% endif %}
<div class="groups_button">
  <div class="button_text">
    <div class="big_text">
      <!--number of groups-->
      34      
    </div>
    groups
  </div>
</div>
<div class="friends_button">
  <div class="button_text">
    <div class="big_text">
      <!--number of friends-->
      34
    </div> 
    friends
  </div>
</div>
{% if request.user != user %}
  <div class="fb_add_button">
    <div class="fb_add_text">
      Add me on Facebook
    </div>
  </div>
{% else %}
  <a href="{% url 'main:edit_user' %}"><div class="edit_button">
    <div class="button_text">
      Edit Profile
    </div>
  </div></a>
{% endif %}
{% endblock %}

HabitHack/main/templates/main/signup.html
{% extends 'main/index.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock content%}